version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./api-server/ApiTestingDB.sql:/docker-entrypoint-initdb.d/ApiTestingDB.sql

  api-server:
    build: ./api-server
    ports:
      - "8888:80"
    depends_on:
      - mysql